import type { PublicLocale } from '../../lib/i18n/locales'

export const publicRouteErrorText: Record<PublicLocale, { eyebrow: string; title: string; description: string; retry: string; menu: string }> = {
  lt: { eyebrow: 'Gio’s Kebab', title: 'Kažkas nepavyko.', description: 'Puslapio nepavyko parodyti. Pabandykite dar kartą arba grįžkite į meniu.', retry: 'Bandyti dar kartą', menu: 'Grįžti į meniu' },
  en: { eyebrow: 'Gio’s Kebab', title: 'Something went wrong.', description: 'We couldn’t show this page. Please try again or return to the menu.', retry: 'Try again', menu: 'Return to menu' },
  ru: { eyebrow: 'Gio’s Kebab', title: 'Что-то пошло не так.', description: 'Не удалось показать страницу. Попробуйте ещё раз или вернитесь к меню.', retry: 'Попробовать снова', menu: 'Вернуться к меню' },
  ka: { eyebrow: 'Gio’s Kebab', title: 'რაღაც შეცდომა მოხდა.', description: 'გვერდის ჩვენება ვერ მოხერხდა. სცადეთ ხელახლა ან დაბრუნდით მენიუში.', retry: 'ხელახლა ცდა', menu: 'მენიუში დაბრუნება' },
}

const en = {
  browseMenu: 'Browse the menu', deliveryThrough: 'Delivery via', chooseDeliveryService: 'Choose a delivery service', reviewOnGoogle: 'Review on Google',
  today: 'Today', viewDetails: 'View details', productDetails: 'Menu details', illustrativeImage: 'Illustrative image',
  skip: 'Skip to content', menu: 'Menu', close: 'Close', language: 'Website language', visit: 'Visit', orderDelivery: 'Order delivery',
  openMenu: 'Open navigation menu', closeMenu: 'Close navigation menu', primaryNav: 'Primary navigation', mobileNav: 'Mobile navigation', backTopLabel: "Gio's Kebab, back to top", logoAlt: "Gio's Kebab logo",
  heroEyebrow: "Gio's Kebab / from the grill", heroLine1: 'The good', heroLine2: 'kind of', heroAccent: 'heat.', heroSubtitle: 'Good food. Good company. A little fire in the middle of it all.', exploreMenu: 'Explore the menu', browseOrderWolt: 'Browse here · Order via Wolt', browseOrderBolt: 'Browse here · Order via Bolt Food', browseOrderBoth: 'Browse here · Order via Wolt or Bolt Food', scroll: 'Scroll to explore',
  checkingToday: "Checking today's hours", todayUnavailable: "Today's hours unavailable", retry: 'Retry', specialToday: 'special schedule today', openNow: 'Open now', until: 'until', opensToday: 'Opens today at', closedNow: 'Closed now', opens: 'opens', tomorrow: 'tomorrow', closedToday: 'Closed today', closedForToday: 'Closed for today',
  menuIndex: 'The menu', menuTitle: 'The menu.', menuAccent: 'All the good stuff.', menuIntro: "A focused menu, straight from Gio's. Find your usual, or find something new.", menuLoading: 'Setting the table…', menuErrorTitle: 'The menu is taking a moment.', menuError: "We couldn't load it right now. Please try again.", reloadMenu: 'Reload menu', menuEmptyTitle: 'Our menu is being updated.', menuEmpty: 'Check back soon for the latest from the grill.', jumpTo: 'Jump to', menuCategories: 'Menu categories', selectedFrom: 'Selected from the menu', featuredItem: 'Featured menu item', featured: 'Featured', soldOutToday: 'Sold out today', soldOut: 'Sold out', item: 'item', items: 'items', fallbackTop: "Gio's / the menu", fallbackBottom: 'Good things take heat.',
  offersIndex: 'Good to know', offersTitle: 'On the', offersAccent: 'board.', offersLoading: "Checking what's on the board…", offersUnavailable: 'Current updates are unavailable.', tryAgain: 'Try again', ends: 'Ends', at: 'at', localTime: 'local time',
  visitIndex: 'Come through', visitTitle: 'Find us.', visitAccent: 'Say hello.', place: 'The place', visitLoading: 'Finding the details…', visitPreparing: 'Visit details are being prepared.', visitUnavailable: "We couldn't load the visit details right now.", directions: 'Get directions', newTab: 'opens in a new tab', when: 'When to drop by', openingHours: 'Opening hours', timezoneHint: "Times shown for the restaurant's local time zone.", hoursLoading: 'Checking opening hours…', hoursUpdating: 'Opening hours are being updated.', hoursUnavailable: "We couldn't load the opening hours right now.", closed: 'Closed', upcoming: 'Upcoming changes', orderKicker: 'A little closer to home', takeWithYou: "Take Gio's with you.", orderOn: 'Order on',
  seeYou: 'See you soon', backTop: 'Back to top', footerLine: 'Good food. No fuss.', metaTitle: 'Menu & Opening Hours', metaFallbackTitle: "Gio's Kebab | From the grill", metaFallbackDescription: "Gio's Kebab. Explore the menu, opening hours, and ways to visit or order.",
  weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  weekdayLabels: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
} as const
type PublicText = { [K in keyof typeof en]: typeof en[K] extends readonly string[] ? readonly string[] : string }

export const publicText: Record<PublicLocale, PublicText> = {
  en,
  lt: {
    browseMenu: 'Peržiūrėkite meniu', deliveryThrough: 'Pristatymas per', chooseDeliveryService: 'Pasirinkite pristatymo paslaugą', reviewOnGoogle: 'Įvertinkite „Google“',
    today: 'Šiandien', viewDetails: 'Peržiūrėti informaciją', productDetails: 'Patiekalo informacija', illustrativeImage: 'Iliustracinis vaizdas',
    skip: 'Pereiti prie turinio', menu: 'Meniu', close: 'Uždaryti', language: 'Svetainės kalba', visit: 'Aplankykite', orderDelivery: 'Užsisakyti pristatymą',
    openMenu: 'Atidaryti navigaciją', closeMenu: 'Uždaryti navigaciją', primaryNav: 'Pagrindinė navigacija', mobileNav: 'Mobilioji navigacija', backTopLabel: "Gio's Kebab, grįžti į pradžią", logoAlt: "Gio's Kebab logotipas",
    heroEyebrow: "Gio's Kebab / nuo grilio", heroLine1: 'Geras', heroLine2: 'skonis su', heroAccent: 'ugnele.', heroSubtitle: 'Geras maistas. Gera kompanija. Šiek tiek ugnies tarp mūsų.', exploreMenu: 'Peržiūrėti meniu', browseOrderWolt: 'Meniu peržiūrėkite čia · Užsisakykite per Wolt', browseOrderBolt: 'Meniu peržiūrėkite čia · Užsisakykite per Bolt Food', browseOrderBoth: 'Meniu peržiūrėkite čia · Užsisakykite per Wolt arba Bolt Food', scroll: 'Slinkti toliau',
    checkingToday: 'Tikriname šiandienos laiką', todayUnavailable: 'Šiandienos laikas nepasiekiamas', retry: 'Bandyti dar kartą', specialToday: 'šiandien galioja specialus laikas', openNow: 'Dabar atidaryta', until: 'iki', opensToday: 'Šiandien atidarome', closedNow: 'Dabar uždaryta', opens: 'atidarome', tomorrow: 'rytoj', closedToday: 'Šiandien nedirbame', closedForToday: 'Šiandien jau uždaryta',
    menuIndex: 'Meniu', menuTitle: 'Meniu.', menuAccent: 'Viskas, kas skanu.', menuIntro: "Trumpas, aiškus Gio's meniu. Raskite mėgstamą patiekalą arba atraskite naują.", menuLoading: 'Ruošiame meniu…', menuErrorTitle: 'Meniu kol kas nepasiekiamas.', menuError: 'Nepavyko jo įkelti. Bandykite dar kartą.', reloadMenu: 'Įkelti meniu iš naujo', menuEmptyTitle: 'Meniu atnaujinamas.', menuEmpty: 'Netrukus čia rasite naujausius patiekalus.', jumpTo: 'Pereiti prie', menuCategories: 'Meniu kategorijos', selectedFrom: 'Iš meniu pasirinkta', featuredItem: 'Išskirtinis meniu patiekalas', featured: 'Išskirtinis', soldOutToday: 'Šiandien išparduota', soldOut: 'Išparduota', item: 'patiekalas', items: 'patiekalai', fallbackTop: "Gio's / meniu", fallbackBottom: 'Geriems dalykams reikia karščio.',
    offersIndex: 'Verta žinoti', offersTitle: 'Kas', offersAccent: 'naujo.', offersLoading: 'Tikriname naujienas…', offersUnavailable: 'Naujienų dabar nepavyko įkelti.', tryAgain: 'Bandyti dar kartą', ends: 'Galioja iki', at: 'val.', localTime: 'vietos laiku',
    visitIndex: 'Užsukite', visitTitle: 'Raskite mus.', visitAccent: 'Pasisveikinkime.', place: 'Adresas', visitLoading: 'Ieškome informacijos…', visitPreparing: 'Apsilankymo informacija ruošiama.', visitUnavailable: 'Dabar nepavyko įkelti apsilankymo informacijos.', directions: 'Kaip atvykti', newTab: 'atidaroma naujame skirtuke', when: 'Kada užsukti', openingHours: 'Darbo laikas', timezoneHint: 'Laikas nurodytas restorano vietos laiku.', hoursLoading: 'Tikriname darbo laiką…', hoursUpdating: 'Darbo laikas atnaujinamas.', hoursUnavailable: 'Dabar nepavyko įkelti darbo laiko.', closed: 'Nedirbame', upcoming: 'Artėjantys pakeitimai', orderKicker: 'Gio’s arčiau namų', takeWithYou: 'Pasiimkite Gio’s su savimi.', orderOn: 'Užsisakyti per',
    seeYou: 'Iki pasimatymo', backTop: 'Grįžti į pradžią', footerLine: 'Geras maistas. Be rūpesčių.', metaTitle: 'Meniu ir darbo laikas', metaFallbackTitle: "Gio's Kebab | Nuo grilio", metaFallbackDescription: "Gio's Kebab. Peržiūrėkite meniu, darbo laiką ir apsilankymo ar užsakymo galimybes.",
    weekdays: ['Sekmadienį', 'Pirmadienį', 'Antradienį', 'Trečiadienį', 'Ketvirtadienį', 'Penktadienį', 'Šeštadienį'],
    weekdayLabels: ['Sekmadienis', 'Pirmadienis', 'Antradienis', 'Trečiadienis', 'Ketvirtadienis', 'Penktadienis', 'Šeštadienis'],
  },
  ru: {
    browseMenu: 'Смотрите меню', deliveryThrough: 'Доставка через', chooseDeliveryService: 'Выберите службу доставки', reviewOnGoogle: 'Оставить отзыв в Google',
    today: 'Сегодня', viewDetails: 'Подробнее', productDetails: 'О блюде', illustrativeImage: 'Иллюстративное изображение',
    skip: 'Перейти к содержимому', menu: 'Меню', close: 'Закрыть', language: 'Язык сайта', visit: 'Как нас найти', orderDelivery: 'Заказать доставку',
    openMenu: 'Открыть меню навигации', closeMenu: 'Закрыть меню навигации', primaryNav: 'Основная навигация', mobileNav: 'Мобильная навигация', backTopLabel: "Gio's Kebab, наверх страницы", logoAlt: "Логотип Gio's Kebab",
    heroEyebrow: "Gio's Kebab / с гриля", heroLine1: 'Вкус', heroLine2: 'с настоящим', heroAccent: 'огоньком.', heroSubtitle: 'Хорошая еда. Хорошая компания. И немного огня между нами.', exploreMenu: 'Смотреть меню', browseOrderWolt: 'Меню смотрите здесь · Заказывайте через Wolt', browseOrderBolt: 'Меню смотрите здесь · Заказывайте через Bolt Food', browseOrderBoth: 'Меню смотрите здесь · Заказывайте через Wolt или Bolt Food', scroll: 'Листайте дальше',
    checkingToday: 'Проверяем часы на сегодня', todayUnavailable: 'Часы на сегодня недоступны', retry: 'Повторить', specialToday: 'сегодня особый график', openNow: 'Сейчас открыто', until: 'до', opensToday: 'Сегодня открываемся в', closedNow: 'Сейчас закрыто', opens: 'откроемся', tomorrow: 'завтра', closedToday: 'Сегодня не работаем', closedForToday: 'Сегодня уже закрыто',
    menuIndex: 'Меню', menuTitle: 'Меню.', menuAccent: 'Всё самое вкусное.', menuIntro: "Небольшое меню Gio's: любимые блюда и новые открытия.", menuLoading: 'Загружаем меню…', menuErrorTitle: 'Меню пока недоступно.', menuError: 'Не удалось загрузить меню. Попробуйте ещё раз.', reloadMenu: 'Загрузить меню снова', menuEmptyTitle: 'Мы обновляем меню.', menuEmpty: 'Скоро здесь появятся блюда с гриля.', jumpTo: 'Перейти к', menuCategories: 'Категории меню', selectedFrom: 'Выбор из меню', featuredItem: 'Рекомендуемое блюдо', featured: 'Рекомендуем', soldOutToday: 'Сегодня закончилось', soldOut: 'Закончилось', item: 'позиция', items: 'позиции', fallbackTop: "Gio's / меню", fallbackBottom: 'Для хорошего вкуса нужен огонь.',
    offersIndex: 'Новости', offersTitle: 'На нашей', offersAccent: 'доске.', offersLoading: 'Проверяем новости…', offersUnavailable: 'Не удалось загрузить новости.', tryAgain: 'Повторить', ends: 'До', at: 'в', localTime: 'по местному времени',
    visitIndex: 'Заходите', visitTitle: 'Найдите нас.', visitAccent: 'Будем рады.', place: 'Адрес', visitLoading: 'Загружаем адрес…', visitPreparing: 'Информация о посещении готовится.', visitUnavailable: 'Не удалось загрузить информацию о посещении.', directions: 'Построить маршрут', newTab: 'откроется в новой вкладке', when: 'Когда заходить', openingHours: 'Часы работы', timezoneHint: 'Время указано по местному времени ресторана.', hoursLoading: 'Проверяем часы работы…', hoursUpdating: 'Часы работы обновляются.', hoursUnavailable: 'Не удалось загрузить часы работы.', closed: 'Закрыто', upcoming: 'Ближайшие изменения', orderKicker: 'Gio’s ближе к дому', takeWithYou: 'Возьмите Gio’s с собой.', orderOn: 'Заказать через',
    seeYou: 'До встречи', backTop: 'Наверх', footerLine: 'Хорошая еда. Без лишних забот.', metaTitle: 'Меню и часы работы', metaFallbackTitle: "Gio's Kebab | С гриля", metaFallbackDescription: "Gio's Kebab. Меню, часы работы и способы посетить нас или заказать доставку.",
    weekdays: ['В воскресенье', 'В понедельник', 'Во вторник', 'В среду', 'В четверг', 'В пятницу', 'В субботу'],
    weekdayLabels: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  },
  ka: {
    browseMenu: 'იხილეთ მენიუ', deliveryThrough: 'მიტანა', chooseDeliveryService: 'აირჩიეთ მიტანის სერვისი', reviewOnGoogle: 'შეაფასეთ Google-ზე',
    today: 'დღეს', viewDetails: 'დეტალების ნახვა', productDetails: 'კერძის დეტალები', illustrativeImage: 'საილუსტრაციო გამოსახულება',
    skip: 'შიგთავსზე გადასვლა', menu: 'მენიუ', close: 'დახურვა', language: 'საიტის ენა', visit: 'გვეწვიეთ', orderDelivery: 'მიტანის შეკვეთა',
    openMenu: 'ნავიგაციის გახსნა', closeMenu: 'ნავიგაციის დახურვა', primaryNav: 'მთავარი ნავიგაცია', mobileNav: 'მობილური ნავიგაცია', backTopLabel: "Gio's Kebab, გვერდის დასაწყისში", logoAlt: "Gio's Kebab-ის ლოგო",
    heroEyebrow: "Gio's Kebab / გრილიდან", heroLine1: 'გემო', heroLine2: 'ცეცხლის', heroAccent: 'ელფერით.', heroSubtitle: 'კარგი საჭმელი. კარგი ადამიანები. და ცოტაოდენი ცეცხლი შუაში.', exploreMenu: 'მენიუს ნახვა', browseOrderWolt: 'მენიუ იხილეთ აქ · შეუკვეთეთ Wolt-ის მეშვეობით', browseOrderBolt: 'მენიუ იხილეთ აქ · შეუკვეთეთ Bolt Food-ის მეშვეობით', browseOrderBoth: 'მენიუ იხილეთ აქ · შეუკვეთეთ Wolt-ის ან Bolt Food-ის მეშვეობით', scroll: 'გადაახვიეთ ქვემოთ',
    checkingToday: 'ვამოწმებთ დღევანდელ საათებს', todayUnavailable: 'დღევანდელი საათები მიუწვდომელია', retry: 'ხელახლა ცდა', specialToday: 'დღეს განსაკუთრებული განრიგია', openNow: 'ახლა ღიაა', until: 'საათამდე', opensToday: 'დღეს გაიხსნება', closedNow: 'ახლა დაკეტილია', opens: 'გაიხსნება', tomorrow: 'ხვალ', closedToday: 'დღეს დაკეტილია', closedForToday: 'დღეს უკვე დაკეტილია',
    menuIndex: 'მენიუ', menuTitle: 'მენიუ.', menuAccent: 'ყველაფერი გემრიელი.', menuIntro: "Gio's-ის მოკლე მენიუ. იპოვეთ საყვარელი კერძი ან აღმოაჩინეთ ახალი.", menuLoading: 'მენიუს ვტვირთავთ…', menuErrorTitle: 'მენიუ ამჟამად მიუწვდომელია.', menuError: 'ჩატვირთვა ვერ მოხერხდა. სცადეთ ხელახლა.', reloadMenu: 'მენიუს ხელახლა ჩატვირთვა', menuEmptyTitle: 'მენიუ ახლდება.', menuEmpty: 'მალე აქ გრილიდან ახალ კერძებს ნახავთ.', jumpTo: 'გადასვლა', menuCategories: 'მენიუს კატეგორიები', selectedFrom: 'შერჩეული მენიუდან', featuredItem: 'რჩეული კერძი', featured: 'რჩეული', soldOutToday: 'დღეს ამოიწურა', soldOut: 'ამოიწურა', item: 'კერძი', items: 'კერძები', fallbackTop: "Gio's / მენიუ", fallbackBottom: 'კარგ გემოს ცეცხლი სჭირდება.',
    offersIndex: 'სიახლეები', offersTitle: 'ჩვენი', offersAccent: 'სიახლეები.', offersLoading: 'სიახლეებს ვამოწმებთ…', offersUnavailable: 'სიახლეები ვერ ჩაიტვირთა.', tryAgain: 'ხელახლა ცდა', ends: 'მოქმედებს', at: 'საათამდე', localTime: 'ადგილობრივი დროით',
    visitIndex: 'შემოგვიარეთ', visitTitle: 'გვიპოვეთ.', visitAccent: 'მოგესალმებით.', place: 'მისამართი', visitLoading: 'ინფორმაციას ვტვირთავთ…', visitPreparing: 'ვიზიტის ინფორმაცია მზადდება.', visitUnavailable: 'ვიზიტის ინფორმაცია ვერ ჩაიტვირთა.', directions: 'მარშრუტის ნახვა', newTab: 'იხსნება ახალ ჩანართში', when: 'როდის გვესტუმროთ', openingHours: 'სამუშაო საათები', timezoneHint: 'დრო მითითებულია რესტორნის ადგილობრივი დროით.', hoursLoading: 'სამუშაო საათებს ვამოწმებთ…', hoursUpdating: 'სამუშაო საათები ახლდება.', hoursUnavailable: 'სამუშაო საათები ვერ ჩაიტვირთა.', closed: 'დაკეტილია', upcoming: 'მომავალი ცვლილებები', orderKicker: 'Gio’s უფრო ახლოს', takeWithYou: 'წაიყოლეთ Gio’s.', orderOn: 'შეკვეთა',
    seeYou: 'მალე გნახავთ', backTop: 'დასაწყისში დაბრუნება', footerLine: 'კარგი საჭმელი. ზედმეტი საზრუნავის გარეშე.', metaTitle: 'მენიუ და სამუშაო საათები', metaFallbackTitle: "Gio's Kebab | გრილიდან", metaFallbackDescription: "Gio's Kebab. ნახეთ მენიუ, სამუშაო საათები და სტუმრობის ან შეკვეთის გზები.",
    weekdays: ['კვირას', 'ორშაბათს', 'სამშაბათს', 'ოთხშაბათს', 'ხუთშაბათს', 'პარასკევს', 'შაბათს'],
    weekdayLabels: ['კვირა', 'ორშაბათი', 'სამშაბათი', 'ოთხშაბათი', 'ხუთშაბათი', 'პარასკევი', 'შაბათი'],
  },
}
